### ISSUE TITLE
Unknown USB Device (Invalid Device Descriptor)

### ISSUE THREAD

**Issue by ovywan** [wagiminator/CH552-MouseWiggler#2]
Hello,

Thank you for this great design. I have assembled this project and I managed to detect the chip and program it from the first try with Arduino.
The programming went flawlessly with the provided source code, but after reconnecting the board to the PC, it is not recognized as a HID mouse, it appears as **Unknown USB Device (Invalid Device Descriptor)**, constantly connecting and disconnecting.

Did you encounter this issue? Do you have any idea what the cause is?

Thank you.

**Comment by wagiminator** [comment]
Hi! I assume you are using Windows. It may be that Windows takes too long to identify the device, causing the watchdog to fire. Try one of the following two modifications to mousewiggler.c:
1. in line 73 increase the "wait for Windows time" in DLY_ms to let's say 1000, or
2. remove the watchdog by deleting lines 73, 76, and 94.

Please report back whether it worked so that I can add the changes here if necessary.

**Comment by ovywan** [comment]
I've tried with an increasing delay up to 5000, no changes...
The watchdog also didn't do anything.

Initially, I used only the Windows 10 PC, but now I've also tried on a RasPi4 and on an Android phone, which does recognize other mice, both commercial and simulated on an ATtiny85 (my previous WFH solution 😃).

I've also tried the other 3 sketches that use USB, with the same result.

Could it be something in the code related to the USB protocol?

Edit:
I forgot about the disconnections... after 33 seconds of running, it resets; always 33 seconds.
When I disable the WDT, the device no longer disconnects, but it freezes, it no longer changes the LED and does not respond to touch.

**Comment by wagiminator** [comment]
Strange. I've tested it again and it works both, on Linux and Windows. Maybe it's because of compiling with the Arduino IDE (I'm using the makefile). When I find the time I will install the Arduino IDE and try it out. If you have Python3 and PyUSB installed somewhere, try uploading the compiled mousewiggler.bin.

**Comment by wagiminator** [comment]
BTW, did you make the proper settings in the Arduino IDE? Maybe try also "USER CODE /w 148B USB ram".

**Comment by ovywan** [comment]
So, in Arduino I've tried every combination of settings, none of which had any success.
But when I installed the precompiled BIN files (I used WCHISPStudio v3.5), I had success with _neotouch_, _capsblock_ and _touchraw_. I'm sure the other 2 would have worked, but it seems that I also need to change the touch calibration.

If you have any idea on how to fix the Arduino compiling, that would be great.

I guess that the BIN files are created from the exactly the same code. I'll now try with _makefile_, since I need to change the configuration to match my board.

Thanks for the suggestions.

**Comment by ovywan** [comment]
_Makefile_ on Linux works perfectly and I was able to update the _config.h_ file and change the code.
The issue is clearly something related to Arduino IDE. I am using Arduino 1.8.13 and used the latest board definition of CH55xDuino MCS51 (v0.0.18). I might test again with the latest Arduino IDE, but I will close this issue.
Thanks again for sharing this awesome project and for the debugging hints.
